name: "Next.js integration status"
author: Turbopack team
description: "Display next.js integration test failure status"

inputs:
  token:
    description: "Github token to use to create test report comment. If not specified, the default token will be used with username 'github-actions'"
    default: ${{ github.token }}

  diff_base:
    description: "The base of the test results to compare against. If not specified, will try to compare with latest main branch's test results."
    default: "main"

  expand_full_result_message:
    description: |
      Include full test failure message in the report.
      This is currently disabled as we have too many failed test cases, leading to
      too many report comments generated.
    default: "false"

runs:
  using: node20
  main: index.js
